blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/y3l1n4ung/pymelos/discussions/categories/q-a
    about: Ask questions and get help from the community
  - name: Ideas & Feature Discussion
    url: https://github.com/y3l1n4ung/pymelos/discussions/categories/ideas
    about: Discuss ideas before creating a feature request
